import { cn } from '#/core/utils'

// Keep the legacy names accepted while callers migrate to the new style API.
export type variant = 'solid' | 'tinted' | 'outlined' | 'plain' | 'text' | (string & {})
export type size = 'default' | 'sm' | 'lg' | 'icon'
export type convey = 'danger' | 'warning' | 'success' | 'info' | 'none'
export type alignment = 'left' | 'right' | 'center'

export interface ButtonStyleProps { variant?: variant; convey?: convey; size?: size; alignment?: alignment; className?: string }

const variants: Record<variant, string> = { solid: 'bg-primary text-primary-foreground hover:bg-[color-mix(in_srgb,hsl(var(--primary))_90%,black_10%)] active:bg-[color-mix(in_srgb,hsl(var(--primary))_81%,black_19%)] dark:hover:bg-[color-mix(in_srgb,hsl(var(--primary))_90%,white_10%)] dark:active:bg-[color-mix(in_srgb,hsl(var(--primary))_81%,white_19%)]', tinted: 'border border-primary/20 bg-primary/10 text-primary hover:bg-primary/20 active:bg-primary/30 dark:border-primary/30 dark:bg-primary/20 dark:hover:bg-primary/30 dark:active:bg-primary/40', outlined: 'border-[color-mix(in_srgb,hsl(var(--primary))_75%,transparent)] bg-transparent text-primary hover:border-[color-mix(in_srgb,hsl(var(--primary))_90%,black_10%)] hover:bg-[color-mix(in_srgb,hsl(var(--primary))_90%,white_10%)] active:border-[color-mix(in_srgb,hsl(var(--primary))_100%,black_20%)] active:bg-[color-mix(in_srgb,hsl(var(--primary))_80%,white_20%)] dark:border-[color-mix(in_srgb,hsl(var(--primary))_75%,transparent)] dark:hover:border-[color-mix(in_srgb,hsl(var(--primary))_90%,white_10%)] dark:hover:bg-[color-mix(in_srgb,hsl(var(--primary))_75%,white_25%)] dark:active:border-[color-mix(in_srgb,hsl(var(--primary))_100%,white_20%)] dark:active:bg-[color-mix(in_srgb,hsl(var(--primary))_65%,white_35%)]', plain: 'border border-transparent bg-transparent text-foreground hover:bg-[color-mix(in_srgb,hsl(var(--primary))_90%,white_10%)] hover:text-primary active:bg-[color-mix(in_srgb,hsl(var(--primary))_80%,white_20%)] active:text-primary dark:hover:bg-[color-mix(in_srgb,hsl(var(--primary))_75%,white_25%)] dark:hover:text-primary dark:active:bg-[color-mix(in_srgb,hsl(var(--primary))_65%,white_35%)] dark:active:text-primary', text: 'border border-transparent bg-transparent text-foreground hover:bg-transparent hover:text-primary active:bg-transparent active:text-primary dark:hover:bg-transparent dark:hover:text-primary dark:active:bg-transparent dark:active:text-primary' }
const sizes: Record<size, string> = { default: 'h-10 px-4 py-2', sm: 'h-9 rounded-md px-3', lg: 'h-11 rounded-md px-8', icon: 'h-10 w-10' }
const alignments: Record<alignment, string> = { left: 'justify-start', center: 'justify-center', right: 'justify-end' }
const conveys: Record<string, string> = { danger: 'bg-red-600 text-white hover:bg-red-700 active:bg-red-800', warning: 'bg-orange-500 text-white hover:bg-orange-600 active:bg-orange-700', success: 'bg-green-600 text-white hover:bg-green-700 active:bg-green-800', info: 'bg-blue-600 text-white hover:bg-blue-700 active:bg-blue-800' }

export function buttonVariants({ variant = 'tinted', convey = 'none', size = 'default', alignment = 'center', className }: ButtonStyleProps = {}) { return cn('inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0', variants[variant as keyof typeof variants] ?? variants.tinted, convey !== 'none' && variant === 'solid' ? conveys[convey] : undefined, sizes[size], alignments[alignment], className) }
